export const recipes = [
    {
      id: 1,
      name: 'Poulet citron',
      ingredients: [
        { ingredient: 'Poulet', quantity: '1.2', unit: 'kg' },
        { ingredient: 'Citrons jaunes', quantity: '200', unit: 'g' },
        { ingredient: 'Ails', quantity: '4', unit: 'gousses' },
        { ingredient: 'Romarin', quantity: '10', unit: 'g' },
        { ingredient: 'Huile d’olive', quantity: '2', unit: 'c. à soupe' },
        { ingredient: 'Sel', quantity: '1', unit: 'pincée' },
        { ingredient: 'Poivre', quantity: '1', unit: 'pincée' },
      ],
      utensils: [
        { utensil: 'Planche à découper' },
        { utensil: 'Cuillère à soupe' },
        { utensil: 'Couteau de cuisine'},
        { utensil: 'Cuillère à café' },
        { utensil: 'Plat pour le four'},
        { utensil: 'Four préchauffé'},
      ],
      tags: ['Four', 'Simple', 'Poulet', 'Léger'],
      totalTime: '1h',
      cookingTime: '50 min',
      prepTime: '10 min',
      nutrition: [
        { quantity: '380', text: 'kcal' },
        { quantity: '42g', text: 'protéines' },
        { quantity: '22g', text: 'glucides' },
        { quantity: '4g', text: 'sucre' },
        { quantity: '1g', text: 'fibres' },
      ],
    },
    {
      id: 2,
      name: 'Tartiflette Savoyarde',
      ingredients: [
        { ingredient: 'Pommes de terre', quantity: '1.2', unit: 'kg' },
        { ingredient: 'Reblochon', quantity: '500', unit: 'g' },
        { ingredient: 'Lardons', quantity: '200', unit: 'g' },
        { ingredient: 'Crème fraîche', quantity: '20', unit: 'cl' },
        { ingredient: 'Oignons', quantity: '2', unit: '' },
        { ingredient: 'Ail', quantity: '2', unit: 'gousses' },
        { ingredient: 'Vin blanc', quantity: '10', unit: 'cl' },
        { ingredient: 'Sel', quantity: '1', unit: 'pincée' },
        { ingredient: 'Poivre', quantity: '1', unit: 'pincée' },
      ],
      utensils: [
        { utensil: 'Planche à découper' },
        { utensil: 'Cuillère à soupe' },
        { utensil: 'Couteau de cuisine'},
        { utensil: 'Cuillère à café' },
        { utensil: 'Plat pour le four'},
        { utensil: 'Four préchauffé'},
      ],
      tags: ['Fromage', 'Savoyarde', 'Chaud', 'Réconfortant'],
      totalTime: '1h 30 min',
      cookingTime: '1h',
      prepTime: '30 min',
      nutrition: [
        { quantity: '550', text: 'kcal' },
        { quantity: '25g', text: 'protéines' },
        { quantity: '45g', text: 'glucides' },
        { quantity: '10g', text: 'lipides' },
        { quantity: '1g', text: 'fibres' },
      ],
    },
    // Ajoute les autres recettes de manière similaire
  ];